config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  
  devise_for :users
  
  resources :projects do
    resources :environments, only: [:show, :new, :create] do
      resources :notifications, only: [:show]
      resources :environment_preferences, only: [:update]
      resources :user_preferences, only: [:update]
    end
    resources :users, only: [:create]
  end

  namespace :api do
    resources :notifications, only: [:create]
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :name, presence: true

  has_and_belongs_to_many :users
  has_many :environments
  
  after_create :create_default_env
  
  def create_default_env
    environments.create!(name: :production)
  end
  
  def environment
    #TODO: return the default environment
    environments.first
  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]

  def index
    @projects = current_user.projects.all
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      @project.users << current_user
      UserPreference.create_default!(current_user.id, @project.environment.id)

      redirect_to project_environment_path(@project, @project.environment)
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      respond_with @project
    else
      render :edit
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_url
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def last_update_to(env)
    if env.notifications.any?
      l env.notifications.last.updated_at, format: :short
    else
      t('messages.never_used')
    end
  end
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
	<%= render 'shared/error', object: @project %>
	
	<div class="form-group">
	  <%= f.label :name %>
	  <%= f.text_field :name, class: "form-control", placeholder: t('attributes.name') %>
	</div>
  <div class="modal-footer">
    <%= f.submit t('form.save'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h3><%=t('title.project.edit')%> <%=@project.name%></h3>

<hr/>

<%= render 'form' %>

app/views/projects/index.html.erb
<h3>
	<%=t('title.project.list')%>
</h3>
<hr />
<div class="col-sm-3 col-md-3">
	<div class="thumbnail add-project" align="center">
		<%= link_to t('form.new'), new_project_path%>
	</div>
</div>
<% @projects.each do |project| %>
<div class="col-sm-3 col-md-3">
	
	<%= link_to project_environment_path(project, project.environment), class: "show-project" do %>
		<div class="thumbnail project-item">
			<%= project.name%> <br/>
			<% project.environments.limit(3).each do |env| %>
				<div class="env-data">
					<span class="env-name"><%=env.name%></span>
					<span class="pull-right last-update">
						<%= last_update_to(env) %>
					</span>
				</div>
			<% end %>
		</div>
	<% end %>
	
</div>
<% end %>

app/views/projects/new.html.erb
<h3><%=t('title.project.new')%></h3>

<hr/>

<%= render 'form' %>

app/views/projects/show.html.erb
<div id="project-show">
	<h3>
		<%= best_in_place @project, :name%>
	</h3>

	<hr />
	
	<!-- notifications -->
	<div>
		<h5><%=t('title.notifications')%></h5>
		<ul class="notifications">
			<% @project.notifications.order(id: :desc).each do |notification| %>
			<li>
				<span class="badge badge-<%=notification.notification_type%>"><%=notification.notification_type%></span>
				<%=link_to notification.url, notification.url, class: 'url'%>
				<span class="updated-at"><%=l notification.updated_at, format: :long%></span>
				<%=link_to "+ Info", project_notification_path(@project, notification), remote: true, class: "more-info"%>
			</li>
			<% end %>
		</ul>
	</div>
	
	<!-- users -->
	<hr />
	<div>
		<h5><%=t('title.users')%></h5>
		
		<ul class="notifications">
			<% @project.users.each do |user| %>
			<li>
				<%=user.email%>
			</li>
			<% end %>
			<li>
				<%= form_for [@project, User.new] do |f| %>
					<%= f.email_field :email, placeholder: t('form.invite_user'), class: 'invite-user' %>
				<% end %>
			</li>
		</ul>
	</div>
	
	<!-- setup -->
	<hr />
	<div>
		<h5>Setup</h5>
		<p class="setup">
			<%=t('messages.setup')%>
		</p>
		
		<div class="well well-lg">
			(function(){
				var js=document.createElement("script");js.type="text/javascript"; 
				js.src="https://www.warnmybug.com/assets/wmb/wmb.js";
				document.head.appendChild(js);
				js.onreadystatechange=js.onload=function(){wmb.track('<%=@project.uid%>');};	
			})();
		</div>
	</div>
</div>