config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  
  devise_for :users
  
  resources :projects do
    resources :environments, only: [:show, :new, :create] do
      resources :notifications, only: [:show]
      resources :environment_preferences, only: [:update]
      resources :user_preferences, only: [:update]
    end
    resources :users, only: [:create]
  end

  namespace :api do
    resources :notifications, only: [:create]
  end
end

app/models/environment.rb
class Environment < ActiveRecord::Base
  
  validates :name, :project_id, presence: true
  belongs_to :project
  has_many :notifications
  has_one :environment_preference
  
  before_create :generate_uid
  after_create :create_preference
  
  def generate_uid
    self.uid = loop do
      random_code = SecureRandom.hex(14).upcase
      break random_code unless Environment.exists?(uid: random_code)
    end
  end
  
  def create_preference
    EnvironmentPreference.create_default!(id)
  end

  def track?(notification_type)
    environment_preference[notification_type]
  end
  
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  before_action :set_project
  
  def new
    @environment = Environment.new
  end
  
  def create
    @environment = @project.environments.new(environment_params)
    
    if @environment.save
      @project.users.each do |user|
        UserPreference.create_default!(user.id, @environment.id)
      end
    
      redirect_to project_environment_path(@project, @environment)
    else
      render :new
    end
  end
  
  def show
    @environment = @project.environments.find(params[:id])
  end
  
  def set_project
    @project = current_user.projects.find(params[:project_id])
  end
  
  def environment_params
    params.require(:environment).permit(:name)
  end

end

app/views/environments/new.html.erb
<h3><%=t('title.environment.new')%></h3>

<hr/>

<%= form_for([@project, @environment]) do |f| %>
	<%= render 'shared/error', object: @environment %>
	
	<div class="form-group">
	  <%= f.label :name %>
	  <%= f.text_field :name, class: "form-control", placeholder: t('attributes.name') %>
	</div>
  <div class="modal-footer">
    <%= f.submit t('form.save'), class: "btn btn-success" %>
  </div>
<% end %>

app/views/environments/show.html.erb
<div id="project-show">
	<h3>
		<%= best_in_place @project, :name%>
		<div class="dropdown pull-right">
		  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
		    <%=@environment.name%>
		    <span class="caret"></span>
		  </button>
			<!-- TODO -->
		  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
				<% @project.environments.each do |env|%>
				<li>
					<%=link_to(env.name, project_environment_path(@project, env)) if env.id != @environment.id%>
				</li>
				<% end %>
		    <li role="separator" class="divider"></li>
				<li>
					<%=link_to(t('title.environment.new'), new_project_environment_path(@project))%>
				</li>
		  </ul>
		</div>
	</h3>

	<hr />

	<!-- notifications -->
	<div>
		<h5><%=t('title.notifications')%></h5>
		<ul class="notifications">
			<% @environment.notifications.order(id: :desc).each do |notification| %>
			<li>
				<span class="badge badge-<%=notification.notification_type%>"><%=notification.notification_type%></span>
				<%=link_to notification.url, notification.url, class: 'url'%>
				<span class="updated-at"><%=l notification.updated_at, format: :long%></span>
				<%=link_to "+ Info", project_environment_notification_path(@project, @environment, notification),
					 remote: true, class: "more-info"%>
			</li>
			<% end %>
		</ul>
	</div>

	<!-- users -->
	<hr />
	<div>
		<h5><%=t('title.users')%></h5>

		<ul class="notifications">
			<% @project.users.each do |user| %>
			<li>
				<%=user.email%>
			</li>
			<% end %>
			<li>
				<%= form_for [@project, User.new] do |f| %>
					<%= f.email_field :email, placeholder: t('form.invite_user'), class: 'invite-user' %>
				<% end %>
			</li>
		</ul>
	</div>

	<!-- setup -->
	<hr />
	<div class='row'>
		<div class='col-sm-6'>
			<h5><%=t('title.env_preferences')%></h5>
			<p>
				<%=form_for([@project, @environment, @environment.environment_preference]) do |f| %>
					<br />
					<b>Track</b> <br /><br />

					<%=f.check_box :log %> <%=f.label :log%><br />

					<%=f.check_box :warn %> <%=f.label :warn%><br />

					<%=f.check_box :error %> <%=f.label :error%><br />

					<br />
					<%=f.submit t('form.save'), class: 'btn btn-default'%>

				<% end %>
			</p>


		</div>

		<div class='col-sm-6'>
			<h5><%=t('title.my_preferences')%></h5>
			<br />
			<%=form_for([@project, @environment, current_user.preference(@environment.id)]) do |f| %>
				<b><%=t('title.notification_preference')%></b> <br /><br />

				<%=f.check_box :email %> <%=f.label :email%><br />

				<br /><br /><br /><br />

				<%=f.submit t('form.save'), class: 'btn btn-default'%>

			<% end %>


		</div>
	</div>


	<!-- setup -->
	<div class="clear-both"></div>
	<hr />
	<div>
		<h5>Setup</h5>
		<p class="setup">
			<%=t('messages.setup')%>
		</p>

		<div class="well well-lg">
			(function(){
				var js=document.createElement("script");js.type="text/javascript";
				js.src="<%= Rails.configuration.raw_settings["domain"] %>/assets/wmb/wmb.js";
				document.head.appendChild(js);
				js.onreadystatechange=js.onload=function(){wmb.track('<%=@environment.uid%>');};
			})();
		</div>
	</div>
</div>