config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'
  
  devise_for :users
  
  resources :projects do
    resources :environments, only: [:show, :new, :create] do
      resources :notifications, only: [:show]
      resources :environment_preferences, only: [:update]
      resources :user_preferences, only: [:update]
    end
    resources :users, only: [:create]
  end

  namespace :api do
    resources :notifications, only: [:create]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Warnmybug</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'wmb/wmb', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>
	<div class="blog-masthead">
		<div class="container">
			<nav class="blog-nav">
				<%= link_to t('menu.projects'), projects_path, class: "blog-nav-item active"%>
				<%= link_to(t('menu.sign_out'), destroy_user_session_path, :method => :delete, class: "blog-nav-item pull-right") %>
			</nav>
		</div>
	</div>
	<div class="container">
	<%= yield %>
	</div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Warnmybug</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
	<style>
	body {
	  padding-top: 40px;
	  padding-bottom: 40px;
	  background-color: #eee;
	}

	.form-signin {
	  max-width: 500px;
	  padding: 15px;
	  margin: 0 auto;
	}
	.form-signin .form-signin-heading,
	.form-signin .checkbox {
	  margin-bottom: 10px;
	}
	.form-signin .checkbox {
	  font-weight: normal;
	}
	.form-signin .form-control {
	  position: relative;
	  height: auto;
	  -webkit-box-sizing: border-box;
	     -moz-box-sizing: border-box;
	          box-sizing: border-box;
	  padding: 10px;
	  font-size: 16px;
	}
	.form-signin .form-control:focus {
	  z-index: 2;
	}
	.form-signin input[type="email"] {
	  margin-bottom: -1px;
	  border-bottom-right-radius: 0;
	  border-bottom-left-radius: 0;
	}
	.form-signin input[type="password"] {
	  margin-bottom: 10px;
	  border-top-left-radius: 0;
	  border-top-right-radius: 0;
	}
	</style>
</head>
<body>
	<div class="container">
		<%=yield%>
	</div>
</div>
</body>
</html>